# Generated by Django 3.0.7 on 2020-06-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='learner',
            name='Other_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.Learner')),
            ],
        ),
    ]
