# Generated by Django 3.0.7 on 2020-06-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20200614_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='last_name',
        ),
    ]
